export interface UsFaqItem {
  q: string;
  a: string;
  qEs?: string;
  aEs?: string;
}

export const usFaqs: UsFaqItem[] = [
  {
    q: "How does 99 Purity Wholesale ensure peptide stability during cross-country transit in the United States?",
    a: "We utilize advanced cold-chain logistics and insulated packaging for temperature-sensitive compounds. Depending on the specific peptide's degradation profile, we may include medical-grade ice packs and utilize expedited shipping networks (2-3 day delivery) to ensure that the molecular integrity of every compound remains completely intact from our USA-based distribution centers to your laboratory bench.",
    qEs: "¿Cómo garantiza 99 Purity Wholesale la estabilidad de los péptidos durante el tránsito por todo Estados Unidos?",
    aEs: "Utilizamos logística avanzada de cadena de frío y embalaje isotérmico para compuestos sensibles a la temperatura. Según el perfil de degradación de cada péptido, podemos incluir acumuladores de frío de grado médico y redes de envío exprés (entrega en 2-3 días) para asegurar que la integridad molecular se mantenga intacta desde nuestros centros de distribución en EE. UU. hasta su laboratorio."
  },
  {
    q: "What are the exact requirements to open a B2B wholesale peptide account in the USA?",
    a: "To partner with us as a bulk buyer, your organization must operate within a relevant scientific, medical, or research capacity. We require a valid Business Employer Identification Number (EIN) or international equivalent, a completed wholesale application detailing your research intent, and verification that the peptides will be used strictly for in-vitro research or laboratory purposes. We do not sell to the general public.",
    qEs: "¿Cuáles son los requisitos exactos para abrir una cuenta mayorista B2B de péptidos en EE. UU.?",
    aEs: "Para colaborar con nosotros como comprador a granel, su organización debe operar dentro de un ámbito científico, médico o de investigación acreditado. Requerimos un Número de Identificación de Empleador (EIN) válido o equivalente internacional, una solicitud mayorista completa detallando su propósito de investigación y la verificación de que los péptidos se utilizarán estrictamente para investigación in vitro o fines de laboratorio. No vendemos al público general."
  },
  {
    q: "Are your Certificates of Analysis (COAs) generated by independent laboratories?",
    a: "Absolutely. We believe that internal testing is a conflict of interest. Every single batch of peptides we distribute undergoes rigorous testing by independent, third-party analytical laboratories based in the United States. We test for chemical purity via HPLC (High-Performance Liquid Chromatography) and verify molecular mass via MS (Mass Spectrometry). The exact COA for your specific batch is provided with every shipment.",
    qEs: "¿Los Certificados de Análisis (COA) son emitidos por laboratorios independientes?",
    aEs: "Absolutamente. Consideramos que las pruebas internas suponen un conflicto de intereses. Cada lote de péptidos que distribuimos se somete a rigurosos análisis en laboratorios analíticos independientes ubicados en Estados Unidos. Evaluamos la pureza química mediante HPLC (cromatografía líquida de alto rendimiento) y verificamos la masa molecular mediante MS (espectrometría de masas). El COA correspondiente a su lote se incluye en cada envío."
  },
  {
    q: "Do you supply bulk GLP-1 agonists like Semaglutide and Tirzepatide to US research institutions?",
    a: "Yes, we are one of the leading domestic suppliers of research-grade GLP-1 receptor agonists. We offer bulk quantities of Semaglutide, Tirzepatide, and Retatrutide for qualified research institutions. Due to high national demand, we maintain robust inventory levels to ensure our B2B partners do not experience supply chain disruptions.",
    qEs: "¿Suministran agonistas GLP-1 a granel como Semaglutide y Tirzepatide a instituciones de investigación en EE. UU.?",
    aEs: "Sí, somos uno de los principales proveedores nacionales de agonistas del receptor GLP-1 de grado de investigación. Ofrecemos cantidades a granel de Semaglutide, Tirzepatide y Retatrutide para instituciones de investigación cualificadas. Debido a la alta demanda nacional, mantenemos niveles sólidos de inventario para asegurar que nuestros socios B2B nunca sufran interrupciones en la cadena de suministro."
  },
  {
    q: "What is the typical turnaround time for a bulk wholesale order shipped domestically?",
    a: "For in-stock compounds, orders are processed and dispatched within 24 hours of payment verification. Standard domestic shipping takes 2 to 4 business days depending on your regional zone (Northeast, Southeast, Midwest, Southwest, or West Coast). Custom synthesis or ultra-high volume orders may require a slightly extended lead time, which your dedicated account manager will communicate upfront.",
    qEs: "¿Cuál es el plazo habitual de entrega para un pedido mayorista a granel con envío nacional?",
    aEs: "Para compuestos en stock, los pedidos se procesan y despachan dentro de las 24 horas posteriores a la confirmación del pago. El envío nacional estándar tarda de 2 a 4 días hábiles según su zona regional (Noreste, Sudeste, Medio Oeste, Sudoeste o Costa Oeste). Los pedidos de síntesis personalizada o de volumen muy elevado pueden requerir un plazo ligeramente mayor, el cual le informará su gestor de cuenta asignado."
  },
  {
    q: "Are peptides purchased from 99 Purity Wholesale legal to possess in all 50 states?",
    a: "Yes, the peptides we supply are legally permitted for possession and use across all 50 U.S. states strictly for research, educational, and laboratory purposes. It is crucial to note that our products are strictly not for human consumption, diagnostic, or therapeutic use. Compliance with local regulations regarding the handling of research chemicals is the responsibility of the purchasing institution.",
    qEs: "¿Es legal poseer en los 50 estados los péptidos adquiridos en 99 Purity Wholesale?",
    aEs: "Sí, los péptidos que suministramos están legalmente autorizados para su posesión y uso en los 50 estados de EE. UU. estrictamente para fines de investigación, educativos y de laboratorio. Es fundamental señalar que nuestros productos no son aptos para consumo humano, ni para uso diagnóstico o terapéutico. El cumplimiento de las normativas locales sobre el manejo de sustancias químicas de investigación corresponde a la institución compradora."
  },
  {
    q: "How does your bulk pricing structure work for US-based laboratories?",
    a: "Our wholesale pricing operates on a tiered volume basis. As your order volume increases, the cost per vial or gram decreases significantly. This structure is designed to support the scalability of high-throughput screening labs and clinical research organizations. We also offer aggressive custom pricing for long-term supply contracts and academic institutions.",
    qEs: "¿Cómo funciona la estructura de precios por volumen para laboratorios en EE. UU.?",
    aEs: "Nuestros precios al por mayor operan mediante una escala escalonada por volumen. A medida que aumenta la cantidad de su pedido, el coste por vial o gramo se reduce notablemente. Esta estructura está diseñada para facilitar la escalabilidad de laboratorios de cribado de alto rendimiento y organizaciones de investigación clínica. Asimismo, ofrecemos precios personalizados altamente competitivos para contratos de suministro a largo plazo e instituciones académicas."
  },
  {
    q: "Do you provide lyophilized (freeze-dried) peptides or pre-mixed solutions?",
    a: "To ensure maximum shelf-life and molecular stability, we exclusively supply lyophilized (freeze-dried) peptide powders. Lyophilization removes water from the compound, preventing hydrolysis and degradation during transit and storage. Researchers must reconstitute the peptides using bacteriostatic water or a suitable solvent immediately prior to their experiments.",
    qEs: "¿Proporcionan péptidos liofilizados (polvo seco) o soluciones premezcladas?",
    aEs: "Para garantizar la máxima vida útil y estabilidad molecular, suministramos exclusivamente polvos de péptidos liofilizados (congelados y secados al vacío). La liofilización elimina el agua del compuesto, evitando la hidrólisis y degradación durante el tránsito y almacenamiento. Los investigadores deben reconstituir los péptidos con agua bacteriostática o un disolvente adecuado inmediatamente antes de sus experimentos."
  },
  {
    q: "Can I request custom peptide synthesis for unique amino acid sequences?",
    a: "Yes, our state-of-the-art synthesis capabilities allow us to produce custom peptide sequences tailored to your specific research protocols. We offer modifications such as N-terminal acetylation, C-terminal amidation, and fluorescent tagging. Minimum order quantities (MOQs) apply for custom synthesis projects. Contact our wholesale team to discuss your specific requirements.",
    qEs: "¿Puedo solicitar síntesis de péptidos personalizada para secuencias de aminoácidos exclusivas?",
    aEs: "Sí, nuestras avanzadas capacidades de síntesis nos permiten fabricar secuencias peptídicas personalizadas adaptadas a sus protocolos de investigación específicos. Ofrecemos modificaciones como acetilación en el extremo N-terminal, amidación en el extremo C-terminal y marcado fluorescente. Se aplican cantidades mínimas de pedido (MOQ) para proyectos de síntesis personalizada. Póngase en contacto con nuestro equipo mayorista para analizar sus requisitos."
  },
  {
    q: "What is your return policy if a batch does not meet the promised purity standards?",
    a: "We stand behind our ≥99% purity guarantee with absolute confidence. If you conduct independent third-party testing that contradicts our provided COA, we will initiate a comprehensive investigation. If a discrepancy is confirmed, we will replace the batch immediately or issue a full refund. Quality and trust are the cornerstones of our national operation.",
    qEs: "¿Cuál es su política de devoluciones si un lote no cumple los estándares de pureza prometidos?",
    aEs: "Respaldamos nuestra garantía de pureza ≥99% con absoluta confianza. Si realiza un análisis independiente con un laboratorio tercero que contradiga el COA suministrado, iniciaremos una investigación completa. De confirmarse alguna discrepancia, reemplazaremos el lote de inmediato o emitiremos un reembolso completo. La calidad y la confianza son la base de nuestras operaciones nacionales."
  },
  {
    q: "How do you handle shipping to extreme climate zones within the US (e.g., Arizona in summer)?",
    a: "We actively monitor weather patterns across our shipping routes. For extreme climate zones, we automatically upgrade the thermal insulation of our packaging and utilize advanced phase-change materials to maintain a stable internal temperature. We also coordinate closely with our logistics partners to ensure expedited delivery and minimize time spent in uncontrolled environments.",
    qEs: "¿Cómo gestionan los envíos a zonas climáticas extremas dentro de EE. UU. (por ejemplo, Arizona en verano)?",
    aEs: "Monitorizamos de forma activa las condiciones meteorológicas a lo largo de nuestras rutas de envío. Para zonas de clima extremo, mejoramos automáticamente el aislamiento térmico de los embalajes y utilizamos materiales de cambio de fase avanzados para conservar una temperatura interna estable. Además, coordinamos estrechamente con nuestras agencias logísticas para asegurar entregas urgentes y minimizar el tiempo en entornos no climatizados."
  },
  {
    q: "What payment methods are accepted for domestic wholesale transactions?",
    a: "We offer secure and flexible payment options tailored for B2B transactions, including ACH transfers, direct bank wires, and major corporate credit cards. For established institutional partners with verified purchase histories, we may extend Net-30 payment terms to align with standard procurement cycles.",
    qEs: "¿Qué métodos de pago aceptan para transacciones mayoristas nacionales?",
    aEs: "Ofrecemos opciones de pago seguras y flexibles adaptadas a transacciones B2B, incluidas transferencias ACH, transferencias bancarias directas y las principales tarjetas corporativas. Para socios institucionales consolidados con historial de compras verificado, podemos conceder condiciones de pago a 30 días (Net-30) para ajustarnos a sus ciclos de adquisición habituales."
  }
];

export function getUsFaqs(locale?: string): { q: string; a: string }[] {
  if (locale === 'es') {
    return usFaqs.map((faq) => ({
      q: faq.qEs || faq.q,
      a: faq.aEs || faq.a,
    }));
  }
  return usFaqs.map((faq) => ({
    q: faq.q,
    a: faq.a,
  }));
}
